---
- name: Create Crowdsec directories
  ansible.builtin.file:
    state: directory
    path: "{{ crowdsec_dir }}/{{ item }}"
    mode: "0755"
    owner: "{{ user }}"
    group: admins
  loop:
    - certs

- name: Template files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ crowdsec_dir }}/{{ item }}"
    mode: "0664"
    owner: root
    group: admins
  loop:
    - docker-compose.yml
    - acquis.yaml
  notify: Restart container

- name: Create proxy network
  community.docker.docker_network:
    name: proxy
    state: present

- name: Start container
  community.docker.docker_compose_v2:
    project_src: "{{ crowdsec_dir }}"
    state: present
    pull: always
    remove_orphans: true

- name: Enroll Engine
  community.docker.docker_container_exec:
    container: crowdsec
    command: "cscli console enroll {{ crowdsec_enroll_key }} "
  register: crowdsec_enroll
