---
image: registry.gitlab.0lzi.com/containers/ansible:main

variables:
  ANSIBLE_CONFIG: ansible.cfg

stages:
  - lint
  - playbooks
  - maintenance
  - deploy

include:
  # lint
  - local: .gitlab/ci/lint/ansible-lint.yml
  # default
  - local: .gitlab/ci/default.yml
  # maintenance
  - local: .gitlab/ci/maintenance/dist-upgrade.yml
  - local: .gitlab/ci/maintenance/gitlab-pull.yml
  # playbooks
  - local: .gitlab/ci/playbooks/unseal.yml
