---
monitoring:
  loki:
    env: prod
    org_id: 1
    url: https://loki.0lzi.com/loki/api/v1/push
    user: loki
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/monitoring')['secret']['loki_password'] | default('changeme') }}"
  mimir:
    env: prod
    org_id: 1
    url: https://mimir.0lzi.com/api/v1/push
    user: mimir
    password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/monitoring')['secret']['mimir_password'] | default('changeme') }}"
