---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start rclone service
  ansible.builtin.systemd:
    name: "rclone-backup.{{ item }}"
    state: started
    enabled: true
    no_block: true
  async: "{{ ansible_check_mode | ternary(0, 86400) }}"
  loop:
    - service
    - timer

- name: Start srv-backup service
  ansible.builtin.systemd:
    name: "srv-backup.{{ item }}"
    state: started
    enabled: true
    no_block: true
  async: "{{ ansible_check_mode | ternary(0, 86400) }}"
  loop:
    - service
    - timer
