diun_dir: "{{ base_dir }}/diun"
diun_template: "{% raw %} Docker tag {{ .Entry.Image }} which you subscribed through {{ .Entry.Provider }} provider has been released.{% endraw %}"
diun_webhook_url: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/discord')['secret']['DIUN_WEBHOOK_URL'] }}"
# diun_webhook_url: "{{ lookup('ansible.builtin.env', 'DIUN_WEBHOOK_URL', default='http://foo.com/bar') }}"
