- name: Create Flavours
  openstack.cloud.compute_flavor:
    cloud:
      auth:
        auth_url: "{{ auth_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        project_name: "{{ project_name }}"
        project_domain_name: Default
        user_domain_name: Default
      region_name: "{{ region_name }}"
    state: "{{ item.state }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    is_public: "{{ item.is_public }}"
  with_items: "{{ flavours }}"
