---
service: grafana
grafana_url: "grafana.0lzi.com"
grafana:
  traefik_labels:
    # grafana main
    traefik/http/routers/grafana/rule: "Host(`{{ grafana_url }}`)"
    traefik/http/routers/grafana/service: "grafana"
    traefik/http/routers/grafana/entrypoints: "websecure"
    traefik/http/routers/grafana/tls/certresolver: "cloudflare"
    traefik/http/routers/grafana/tls: "true"
    traefik/http/routers/grafana/middlewares: "crowdsec@consul"
    # grafana service
    traefik/http/services/grafana/loadbalancer/servers/0/url: "http://dockerhost-1.0lzi.com:3000"
