---
grafana_services__to_merge:
  - grafana
service: grafana
grafana_url: "grafana.0lzi.com"
grafana:
  traefik_labels:
    # grafana main
    traefik/http/routers/grafana/rule: "Host(`grafana.0lzi.com`)"
    traefik/http/routers/grafana/service: "grafana"
    traefik/http/routers/grafana/entrypoints: "websecure"
    traefik/http/routers/grafana/tls/certresolver: "cloudflare"
    traefik/http/routers/grafana/tls: "true"
    traefik/http/routers/grafana/middlewares/0: "crowdsec@consul"
    traefik/http/routers/grafana/middlewares/1: "http-rfc1918"
    # grafana service
    traefik/http/services/grafana/loadbalancer/servers/0/url: "http://dockerhost-1.0lzi.com:3000"
