---
openbao_url: "https://github.com/openbao/openbao/releases/download/v{{ openbao_version }}/bao-hsm_{{ openbao_version }}_linux_amd64.deb"
openbao_cluster_name: "openbao_servers"
openbao_version: "2.4.3"
openbao_config_dir: "/etc/openbao.d"
openbao_data_dir: "/opt/openbao/data"
openbao_cert_dir: "{{ openbao_config_dir }}/certs"
openbao_log_dir: "/var/log/openbao"
openbao_self_signed_cert_dir: "/opt/openbao/tls"
openbao_metrics: true
openbao_tls:
  enabled: false
  self_signed: false
  letsencrypt: true
