- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https

# Manual works
# - name: Add docker official gpg
#   ansible.builtin.command: mkdir -m 0755 -p /etc/apt/keyrings

# - name: get docker gpg
#   ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# - name: Setup docker repo
#   ansible.builtin.command:
#    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian
#    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null


# Look to change below for :
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/deb822_repository_module.html

- name: Add sign key avoiding apt_key
  when:
    - not ansible_check_mode
  block:
    - name: Add Signing Key
      ansible.builtin.get_url:
        url: https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc # Needs the asc extension
        mode: '0644'
        force: true

    - name: Docker apt source
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc]
          https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }}
          {{ ansible_distribution_release }} stable
        state: present

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started

- name: Add {{ user }} to docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true
