---
loki_services__to_merge:
  - loki
loki_dir: "{{ base_dir }}/loki"
loki_image: grafana/loki:3.5.5
loki_url: "loki.0lzi.com"
loki_server:
  filesystem: local
## Alternatives
# filesystem: s3
# s3_access: <s3_access_key>
# s3_secret_key: <s3_secret_key>
# s3_url: <s3_url>
# s3_bucket: loki
loki_user: loki
loki_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'ansible/monitoring')['secret']['loki_password'] }}"
loki:
  env: prod
  org_id: 1
  traefik_labels:
    # Loki main interface
    traefik/http/routers/loki/rule: "Host(`loki.0lzi.com`)"
    traefik/http/routers/loki/service: "loki"
    traefik/http/routers/loki/entrypoints: "websecure"
    traefik/http/routers/loki/tls/certresolver: "cloudflare"
    traefik/http/routers/loki/tls/domains/0/sans/0: "loki.0lzi.com"
    traefik/http/routers/loki/middlewares/0: "crowdsec@consul"
    traefik/http/routers/loki/middlewares/1: "http-rfc1918"
    traefik/http/routers/loki/middlewares/2: "{% if loki_password %}loki_auth{% endif %}"
    traefik/http/routers/loki/tls: "true"
    traefik/http/services/loki/loadbalancer/servers/0/url: "http://dockerhost-1.0lzi.com:3100"
    traefik/http/middlewares/loki_auth/basicauth/users: >-
      {{ loki_user }}:{{ loki_password | password_hash('md5_crypt', salt=loki_url[:8]) }}
    traefik/http/middlewares/loki_auth/basicauth/realm: loki
